### ISSUE TITLE
Is there a way to use another url format?

### ISSUE THREAD

**Issue by pr3ssh** [depaolim/django_auth_media#8]
Hi @depaolim.
Thanks in advance for this Django App. It works great. But I have a question: is there a way to use another url format to serve files? For example, Django provides with FileField a "files/%Y/%m/%d/" possibility. it can be used with auth_media instead of /mediafiles/app_name/app_model/if/folder structure provided for the App?

**Comment by depaolim** [comment]
Hi @pr3ssh , thanks for your appreciation

> But I have a question: is there a way to use another url format to serve files? 

not at the moment, but we can evaluate the possibility

> For example, Django provides with FileField a "files/%Y/%m/%d/" possibility.

could you please give me some other detail? (sample/snippet/link-to-doc...)
 
> it can be used with auth_media instead of /mediafiles/app_name/app_model/if/folder structure provided for the App?

At the moment auth_media uses a url that contains back app_label, object_name, object_pk and field_name.
So the view receives all the informations needed to locate uniquely the file and build the correct response

If we use another url pattern there should be a sort of "remapping" to the unique identified file

This makes me think that maybe you could simply define the desired urls and link them to an ad hoc view that implements a redirect to a url built with the auth_media url pattern rules....

**Comment by pr3ssh** [comment]
Thanks for this quick reply. I suggested that for two main reasons:

* Don't download a file called *fieldfile* istead of real file name
* Dont show the AppName/AppModel to the user

I will continue thinking how to imporove that and if I have any suggestion I can make a PR ;)

**Comment by depaolim** [comment]
> * Don't download a file called fieldfile istead of real file name
> * Dont show the AppName/AppModel to the user

Yes, they are two good reasons

> I will continue thinking how to imporove that and if I have any suggestion I can make a PR ;)

Appreciated!

**Comment by pr3ssh** [comment]
I would try to do it.
